

FROM oven/bun:1.0 as build

WORKDIR /app

COPY package.json bun.lockb ./
COPY tsconfig.json ./
COPY next.config.mjs ./
COPY public ./public
COPY src ./src

RUN bun install --frozen-lockfile

RUN bun run build


FROM oven/bun:1.0-slim as production

WORKDIR /app

COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/public ./public
COPY --from=build /app/next.config.mjs ./

EXPOSE 3000

CMD ["bun", "run", "start"]