name: Build e Deploy via Heroku Container Registry

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Login no Heroku Container Registry
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      # Build da imagem Docker de produção
      - name: Build Docker image
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_FRONTEND }}
        run: |
          docker build -t registry.heroku.com/$HEROKU_APP_NAME/web .

      # Push da imagem para o Heroku Container Registry
      - name: Push image to Heroku Container Registry
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_FRONTEND }}
        run: |
          docker push registry.heroku.com/$HEROKU_APP_NAME/web

      # Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Release da aplicação no Heroku
      - name: Release application on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_FRONTEND }}
        run: |
          heroku container:release web --app $HEROKU_APP_NAME
