name: Deploy Frontend (Next.js) to Heroku

on:
  push:
    branches:
      - master
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy-frontend.yml" # Opcional: roda se o próprio workflow for alterado

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_FRONTEND }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

          appdir: "apps/web"
